export const projectsData = {
    "Web Apps": [
        {
            id: 1,
            title: "Gestor de Tareas",
            image: "/projects/task-manager.jpg",
            description: "Aplicación para gestionar tareas con autenticación y sincronización en la nube.",
            website: "https://tugestor.com",
            github: "https://github.com/tuusuario/gestor-tareas",
        },
        {
            id: 2,
            title: "Dashboard Financiero",
            image: "/projects/finance-dashboard.jpg",
            description: "Dashboard interactivo para visualizar gastos e ingresos en tiempo real.",
            website: "https://tudashboard.com",
            github: "https://github.com/tuusuario/finance-dashboard",
        },
        {
            id: 3,
            title: "E-commerce Tienda",
            image: "/projects/ecommerce.jpg",
            description: "Tienda en línea con carrito de compras y pasarela de pago integrada.",
            website: "https://tutienda.com",
            github: "https://github.com/tuusuario/ecommerce",
        },
    ],
    "Landing Pages": [
        {
            id: 4,
            title: "Landing de Producto",
            image: "/projects/product-landing.jpg",
            description: "Página de presentación para un producto con secciones interactivas.",
            website: "https://tuproducto.com",
            github: "https://github.com/tuusuario/product-landing",
        },
        {
            id: 5,
            title: "Landing de Agencia",
            image: "/projects/agency-landing.jpg",
            description: "Página de inicio para una agencia creativa con animaciones modernas.",
            website: "https://tuagencia.com",
            github: "https://github.com/tuusuario/agency-landing",
        },
        {
            id: 6,
            title: "Landing de Evento",
            image: "/projects/event-landing.jpg",
            description: "Sitio web para promocionar un evento con formulario de registro.",
            website: "https://tuevento.com",
            github: "https://github.com/tuusuario/event-landing",
        },
    ],
    "Juegos": [
        {
            id: 7,
            title: "Juego de Memoria",
            image: "/projects/memory-game.jpg",
            description: "Juego de cartas de memoria interactivo con diferentes niveles de dificultad.",
            website: "https://tumemoria.com",
            github: "https://github.com/tuusuario/memory-game",
        },
        {
            id: 8,
            title: "Plataformas 2D",
            image: "/projects/platform-game.jpg",
            description: "Juego de plataformas 2D con física y enemigos dinámicos.",
            website: "https://tuplataforma.com",
            github: "https://github.com/tuusuario/platform-game",
        },
        {
            id: 9,
            title: "Trivia Challenge",
            image: "/projects/trivia-game.jpg",
            description: "Juego de preguntas y respuestas con puntuaciones y categorías variadas.",
            website: "https://tutrivia.com",
            github: "https://github.com/tuusuario/trivia-game",
        },
    ],
};